github:
  description: "Apache Sling Servlet Annotations Integration Tests (deprecated)"
  homepage: "https://sling.apache.org/"
  labels:
    - sling
    - java
    - annotations
    - servlets
    - deprecated
